services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "9898:6379"
    command: >
      redis-server
      --bind 0.0.0.0
      --port 6379
      --aclfile /usr/local/etc/redis/users.acl
      --appendonly yes
      --protected-mode yes
    volumes:
      - redis_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    restart: unless-stopped

volumes:
  redis_data:
